### PR TITLE
Added todo list.

### PR DESCRIPTION
**Pull request by JamesCoyle**
Some things I feel need to be considered.

### CODE REVIEW

**Comment by silvestreh** [comment]
This is not something that should be in the repository. That's what issues are for :smile:

**Comment by JamesCoyle** [comment]
The problem with that is that the issues are for the master branch. It would be confusing creating issues about an unreleased branch. I figured this would be the best option to keep a list of features planned which could be removed before merging with the master branch.

**Comment by silvestreh** [comment]
Check issue #79 we have a list going on there.

**Comment by silvestreh** [comment]
Also, issues aren't always bugs. They're also feature requests, or questions. Just remember to mention the branch you're referring to and we should be golden.

**Comment by equinusocio** [comment]
:+1:

**Pull request closed without merging**
