### PR TITLE
Added orange to the accent color menu

### PR DESCRIPTION
**Pull request by thunsaker**
I like orange.

image

### CODE REVIEW

**Comment by equinusocio** [comment]
Do you used the material design color palette? can you post the #hex code?

**Comment by silvestreh** [comment]
Merged!

**Comment by thunsaker** [comment]
Awesome, thanks!

I was thinking, if other people do the same thing I did, you may want to add a custom color option so people can use whatever color they want. There are already some pre-existing md-color variables that are unused and some people may want to use a custom color that isn't official Material Design.

**Comment by silvestreh** [comment]
Yeah, I actually planned to add all those md-color variables, but I thought it might be too much.

**Pull request merged**
