### PR TITLE
Some UI improvements

### PR DESCRIPTION
**Pull request by equinusocio**
Update input field animation
input_animation

Improve the active tab animation
Removed accent color from tab ripple (the ripple must be non-intrusive) i think it’s better have a  ripple color configuration.
tab_animation

Added option to set different color style (darker, default and lighter). You have to disable it for now.

I hope you like this improvements, if you don’t know me, i’m the author of Sublime Text material theme

### CODE REVIEW

**Comment by equinusocio** [comment]
If you want i can help to rewrite this theme to make it more structured and maintainable.

**Comment by silvestreh** [comment]
I like the changes overall. The input animation breaks in the settings-view. The underline effect is on the `<section>`. Making mini text-editors position's relative kinda fixes it. Also, all animations should have an option to be turned off… I found some people don't appreciate them, even though motion is a key element of Material Design.

I'd love some help, yeah. This is the first Atom theme I made, it started as a Atom Dark UI fork. Most of the theme structure came from there.

**Comment by equinusocio** [comment]
i've fixed the input animation, i suggest you to remove the settings to disabling animations, you can't follow all requests. It's likely ask Google to remove android Lollipop animation because i don't like it. This is the software, you're right, one of the key elements in the MD is "motion", so you can't remove it.

**Comment by silvestreh** [comment]
Well, in Android you actually can disable animations in developers settings. It's a rather obscure setting, but it's there… I actually liked the icons. I find them useful. I usually have a few files with the same name representing different parts of a given feature and the file extension is not enough (not for me at least)… ie. some-feature.html / some-feature.js / some-feature.scss

If you can revert that commit I'll merge your pull request in a heart beat as I really dig what you did.

**Comment by equinusocio** [comment]
@silvestreh you don't recognize the type of the file you're watching? I think this icon is a distraction. I can restore and resize it a bit. You agree?

**Comment by silvestreh** [comment]
Well yes, incredible as it sounds, icons give me a visual cue and I find them helpful. The theme had no icons in tabs a few versions ago and I was really when I added them. Besides, there's nothing in the MD guidelines agains the use of icons in tabs (as long as all tabs have icons and text, all have only text, or all have only icons.) :smiley:

**Comment by equinusocio** [comment]
We can use only icons and text in two separate lines... pff
https://www.google.com/design/spec/components/tabs.html#tabs-usage

**Comment by silvestreh** [comment]
Oh well, let's get rid of them then… I rather have no icons than a huge, 72dp tab. I'll merge your PR.

**Comment by equinusocio** [comment]
@silvestreh if you want, you can make me collaborator.

**Comment by silvestreh** [comment]
@equinusocio Done! :smiley:

**Comment by equinusocio** [comment]
:+1:  :)

**Pull request merged**
